name       : mate-notification-theme-solus
version    : 1
release    : 1
source     :
    - https://github.com/solus-project/mate-notification-theme-solus/releases/download/v1/mate-notification-theme-solus-1.tar.xz : b838d3d4a7b9a34120625b0f9075d84fed0ec4f027e7ccd0104ec214f6e73f56
license    : LGPL-2.1
component  : desktop.mate
summary    : The Solus MATE Notification Daemon theme
description: |
    This provides a notification style identical to the Arc-styled Budgie Desktop notifications.
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - mate-notification-daemon
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
