name       : mate-notification-theme-solus
version    : 2
release    : 2
source     :
    - https://github.com/solus-project/mate-notification-theme-solus/releases/download/v2/mate-notification-theme-solus-2.tar.xz : aaca745f4632fe465498d940790541f43437769a7251bd42708a0a13375c99b4
license    : LGPL-2.1
component  : desktop.mate
summary    : The Solus MATE Notification Daemon theme
description: |
    This provides a notification style identical to the Arc-styled Budgie Desktop notifications.
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - mate-notification-daemon
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
