name       : mate-notification-theme-solus
version    : 3
release    : 3
source     :
    - https://github.com/solus-project/mate-notification-theme-solus/releases/download/v3/mate-notification-theme-solus-3.tar.xz : 3f6722b7ab44e54eb82a14fe1af52da240c210e5304678276c82a0529fb2fe0f
license    : LGPL-2.1
component  : desktop.mate
summary    : The Solus MATE Notification Daemon theme
description: |
    This provides a notification style identical to the Arc-styled Budgie Desktop notifications.
builddeps  :
    - pkgconfig(gtk+-3.0)
rundeps    :
    - mate-notification-daemon
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
